# 用户角色常量
USER_ROLE_ADMIN = "admin"
USER_ROLE_USER = "user"

# 用户角色列表
USER_ROLES = [USER_ROLE_ADMIN, USER_ROLE_USER]

# 文章类型常量
ARTICLE_TYPE_NEWS = "news"
ARTICLE_TYPE_INTERPRETATION = "interpretation"

# 文章类型列表
ARTICLE_TYPES = [ARTICLE_TYPE_NEWS, ARTICLE_TYPE_INTERPRETATION]

# 文章状态常量
ARTICLE_STATUS_DRAFT = "draft"
ARTICLE_STATUS_PUBLISHED = "published"
ARTICLE_STATUS_OFFLINE = "offline"

# 文章状态列表
ARTICLE_STATUSES = [ARTICLE_STATUS_DRAFT, ARTICLE_STATUS_PUBLISHED, ARTICLE_STATUS_OFFLINE]
